### ISSUE TITLE
Submission: implement python parser for template

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/ecosystem#10]
### What is the expected behavior?

Submission for membership in ecosystem is handled through github issues. Specifically using[ submission template](https://github.com/qiskit-community/ecosystem/blob/main/.github/ISSUE_TEMPLATE/submission.yml). 
In order to make use of information inside issue we need to implement a parser, which will extract all necessary information. 
Later on we will use this information in CI processes and save it to json db

A.k.a we need to implement function:
```python
def parse_submission_issue(body_of_issue: str) -> Repository:
    """Parses body of issue and creates Repository object."""
    ...
```

**Related story:**  as community member of ecosystem I want to be able to submit my project so that it would be included into ecosystem

**Epic** #9

**Comment by mickahell** [comment]
assign it to me
