### ISSUE TITLE
Skip dev and stable tests if there is no dependency on Qiskit

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/ecosystem#106]
### What is the expected enhancement?
Skip dev and stable tests if there is no dependency on Qiskit

**Comment by IceKhan13** [comment]
One option might be include this in project configuration

**Comment by mickahell** [comment]
Adding a var in the ecosystem.json saying ```qiskit: false``` if there is no qiskit in the project ?

**Comment by IceKhan13** [comment]
yes

**Comment by IceKhan13** [comment]
Closing it for now as we have `skip_tests` flag which we can use, as we are interested in tests only if there is a dependency
