### ISSUE TITLE
Docs: readme improvements

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/ecosystem#11]
### What is the expected enhancement?

- Improve [readme template](https://github.com/qiskit-community/ecosystem/blob/main/ecosystem/templates/readme.md) for better readability. 
- Incorporate tests results in descriptions. 
- Split into template hierarchy. See [template inheritance](https://jinja.palletsprojects.com/en/3.0.x/templates/#template-inheritance)

**Related stories:**  
- as community member of ecosystem I want my project to be displayed in ecosystem github README and qiskit.org
- as core team member/curator I want README for repository to be generated automatically after each change of members

**Epic** #9

**Comment by mickahell** [comment]
Other points :

-     Add tox.ini template
-     Add repo structure example
-     Add setup.py template

**Comment by IceKhan13** [comment]
closed in #54
