### ISSUE TITLE
Add configurations for project in community tier

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/ecosystem#118]
### What is the expected enhancement?
In #116 we added support for storing configurations for projects in DB.
Now we need to update `members.json` file with configuration for projects.

Example:
https://github.com/qiskit-community/ecosystem/blob/110b47a30c6821d08ddd472939715aa20c6f495b/ecosystem/resources/members.json#L467-L483

**Comment by mickahell** [comment]
This issue could be useful to be sure to not miss something in the file ;) https://github.com/qiskit-community/ecosystem/issues/120
