### ISSUE TITLE
Python script: coverage tests for projects

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/ecosystem#13]
### What is the expected behavior?

Implement function to run coverage tests for specified repository against stable version of qiskit.

See [python runner](https://github.com/qiskit-community/ecosystem/pull/8/files#diff-2a724697aa06f1db8af7b6184d0714048fb567e09688288ef3d885c9e19e9bc1R71) for getting the idea. 

Runner should handle execution workflow for coverage and return summary

**Related stories:**  
- as core team member/curator I want CI processes takes care of tests, style checks, coverage after submission so that it would reduce time of review of submission
- as core team member/curator I want checks and tests to have Terra version associated with them so that we can track which version is breaking the code
- as core team member/curator I want CI for tests/checks to be executed in timely manner (weekly) so that entire ecosystem always remains up-to-date

**Epic** #9

**Comment by mickahell** [comment]
Do you have any idea of tools to use ? I find this [Coverage](https://coverage.readthedocs.io/en/coverage-5.5/), so it will just need to replace the test cmd by `coverage run -m unittest discover` and then write `coverage report`or `coverage report --fail-under XX` as show in the image next :

<img width="713" alt="Capture d’écran 2021-09-22 à 22 35 49" src="https://user-images.githubusercontent.com/20951376/134417907-4c749858-b27a-41fb-a9ab-2c55d2727f96.png">
y

**Comment by mickahell** [comment]
if it's ok for you, you can assign it to me :)

**Comment by IceKhan13** [comment]
@mickahell if you look in tox file for our repo we already have coverage, we just do not execute it yet in CI :) 
So your finding is right on point!

https://github.com/qiskit-community/ecosystem/blob/main/tox.ini

**Comment by mickahell** [comment]
Hmm ok, so just need to add in the models/configurations.py file the command for coverage and that's all ?

**Comment by IceKhan13** [comment]
I think you just need to adapt existing one for coverage and that is it :)

**Comment by mickahell** [comment]
Oki doki, that's looks good to me :)

**Comment by mickahell** [comment]
assign it to me

**Comment by IceKhan13** [comment]
already did  ;)

**Comment by mickahell** [comment]
I was thinking the assign to me was for a bot or an autom feature from GitLab

**Comment by IceKhan13** [comment]
no, it's just I can only assign issue to people who commented on issue at least once :)

**Comment by mickahell** [comment]
Does the template `configured_tox.ini` is use only for dev qiskit version or any version ?

**Comment by IceKhan13** [comment]
it is used for everything and would be used for coverage too :)

**Comment by mickahell** [comment]
so what is the difference with the template tox.ini ?

**Comment by IceKhan13** [comment]
I think it was there just for testing purposes. It looks like it is a redundant file which is not used anywhere.
I'm working on refactoring now and will create PR in a few hours you will see. It's going to be a lot of rearrengements and removing of unnecessary code. I'll ping you in PR

**Comment by IceKhan13** [comment]
oh, you actually might be right. Let's use separate template for linter

**Comment by mickahell** [comment]
For linter I just cp the same as for our repo into the template directory

**Comment by IceKhan13** [comment]
I know :)

**Comment by mickahell** [comment]
deleted branch to restart cleanly from last commit, lot of things was messy...
