### ISSUE TITLE
Python script: style checks 

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/ecosystem#14]
### What is the expected behavior?

Implement function to run style checks for specified repository using specific linter configuration (from Qiskit-terra).

See [python runner](https://github.com/qiskit-community/ecosystem/pull/8/files#diff-2a724697aa06f1db8af7b6184d0714048fb567e09688288ef3d885c9e19e9bc1R71) for getting the idea. 

Runner should handle execution workflow for style checks and return summary

**Related stories:**  
- as core team member/curator I want CI processes takes care of tests, style checks, coverage after submission so that it would reduce time of review of submission
- as core team member/curator I want checks and tests to have Terra version associated with them so that we can track which version is breaking the code
- as core team member/curator I want CI for tests/checks to be executed in timely manner (weekly) so that entire ecosystem always remains up-to-date

**Epic** #9

**Comment by mickahell** [comment]
assign it to me

**Comment by mickahell** [comment]
Do you think it's better to have a fresh new function in the runner or I can put it in the [workload](https://github.com/qiskit-community/ecosystem/blob/main/ecosystem/controllers/runner.py#L86) function ?

**Comment by IceKhan13** [comment]
@mickahell I think let's create new Runner instance and name it somehow `PythonStyleCheckRunner` and rename old `PythonRunner` to `PythonTestsRunner` or something like that :)

**Comment by mickahell** [comment]
Let's do that 👍
