### ISSUE TITLE
Some tests results has old versions on qiskit

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/ecosystem#155]
### Steps to reproduce the problem

- go to https://qiskit.org/ecosystem
- scroll and expand quantum-cat project

### What is the current behavior?

Some tests results has old versions on qiskit

### What is the expected behavior?

Test results should only have latest stable version for `stable`,  latest version for  `dev` and defined in `reqiurements.txt` for `standand`

<img width="799" alt="Screen Shot 2022-06-23 at 3 37 25 PM" src="https://user-images.githubusercontent.com/8796709/175383185-c1e7b90a-3089-4cf6-bcd2-b14fbcea8266.png">

**Comment by IceKhan13** [comment]
@1ucian0 it is there under `quantumcat`, not `quantum-cat` :) 

https://github.com/qiskit-community/ecosystem/blob/main/ecosystem/resources/members.json#L1445

**Comment by 1ucian0** [comment]
ahhrj. of course. Sorry
