### ISSUE TITLE
Units tests with secret var

### ISSUE THREAD

**Issue by mickahell** [qiskit-community/ecosystem#161]
### What is the expected enhancement?
In order to run units tests, some projects needs secret var. Else tests are unable to run properly on the ecosystem Actions, because it wouln'd have those vars.

We want to find a way to have enable those tests or to skip them keeping the % of tests coverage as it should.

**Comment by mickahell** [comment]
To use the secret vars we need to add in the `[testenv]` of the `tox.ini` file : `passenv = *`

**Comment by mickahell** [comment]
@IceKhan13 can you add some labels please :) as help-wanted and enhancement.

**Comment by IceKhan13** [comment]
Closing this as not needed at this moment
