### ISSUE TITLE
CONTRIBUTING.md is outdated

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-community/ecosystem#173]
### The problem

The commands to run tox in `CONTRIBUTING.md` are outdated (and maybe too much explanation on unrelated things like Qiskit and Git?). `python manager.py standard_tests <url_of_the github_repository> --tox_python=py39` seems not to be the current way to run standar tests on a repo.

### What is the expected behavior?

For example, `python manager.py standard_tests <url_of_the github_repository> --tox_python=py39` should be replaced by `python manager.py python_standard_tests <url_of_the github_repository>`.

**Comment by Beatrix-droid** [comment]
could you assign this to me please?

**Comment by IceKhan13** [comment]
@Beatrix-droid Assigned!

thank you for taking it 😄

**Comment by Beatrix-droid** [comment]
Thanks, will fix it by Tomorrow

**Comment by mickahell** [comment]
Done in #182
