### ISSUE TITLE
[Submission]: QPong

### ISSUE THREAD

**Issue by Unathi-Skosana** [qiskit-community/ecosystem#179]
### Github repo

https://github.com/HuangJunye/QPong

### Description

A quantum version of the classic game Pong built with Qiskit and PyGame

### Email

ukskosana@gmail.com

### License

Apache License 2.0

### Tags

game

**Comment by Unathi-Skosana** [comment]
Currently the branch [feature/improve-coverage-score](https://github.com/HuangJunye/QPong/tree/feature/improve-coverage-score) satisfies the minimum requirements which should merged with main in due time, I've opened a submission PR in the meantime.

**Comment by HuangJunye** [comment]
PR https://github.com/HuangJunye/QPong/pull/57 has been [merged into main branch](https://github.com/HuangJunye/QPong/pull/58) https://github.com/HuangJunye/QPong. Now it's ready to be added to ecosystem!
