### ISSUE TITLE
Badging system

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/ecosystem#18]
### What is the expected behavior?

Implement badging system for members of ecosystem.

Badging should be dynamic and reflect state of json db with members. 

Potential solution: https://github.com/marketplace/actions/dynamic-badges

Readme should have collapsable section for each of member of ecosystem which has code of badge, so developers can add this code in their readme to showcase status of membership.

Later on we will implement CI to submit badging for members repositories. 

**Related stories**: as core team member/curator I want badging system to be automated so that badges dynamically checks repository membership (ex: gray if checks did not passed or purple of checks passed)

**Epic**: #9

**Comment by mickahell** [comment]
I have an idea :) can you assign it to me please 😬
