### ISSUE TITLE
Ecosystem configuration refactoring

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/ecosystem#19]
### What is the expected behavior?

Review [ecosystem configuration files](https://github.com/qiskit-community/ecosystem/pull/8/files#diff-9153cdb55b0100d3701e774131e8d297c5172b1503538c73e97d524b811a0845R77). 

Currently configuration supports extra dependencies and tests commands and only works for python repositories and using tox as testing and configuration (which is good actually and follows other Qiskit projects)

We need at least to add extra configurable commands to run style checks and coverage. 

**Epic**: #9

**Comment by mickahell** [comment]
bouh :p

**Comment by IceKhan13** [comment]
I think we need to address number of issue in current configuration setup:
1. rename file appropriately. `qe_config.json` is not the best option
2. we have this snippet in 3 runner files (coverage, tests, lint) which is not good. We should hide it inside configuration class or refactor somehow https://github.com/qiskit-community/ecosystem/blob/ac1c4a05ec1150f33593ce64dfeffca89465aa3a/ecosystem/runners/python_coverages_runner.py#L41-L50
3. Optional: move from json to yaml (as all configs usually in yaml) 
4. Maybe store configuration class inside `Repository` class and store in db too. So this configuration will be deafult: if repository has config file -> we use it, if not -> we use config stored in DB

**Comment by mickahell** [comment]
https://github.com/qiskit-community/ecosystem/pull/39#issuecomment-928296839
