### ISSUE TITLE
Submission workflow improvements

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/ecosystem#223]
### What is the expected enhancement?

- [ ] add tier in submission form
- [x] update pr on issue update (#453)
- [ ] turn of issue tests

**Comment by mickahell** [comment]
Hola @IceKhan13 :)
what do you mean by :
> [ ] turn of issue tests

?

**Comment by IceKhan13** [comment]
tests were failing a lot and what I thought is to turn off tests on submission. Only run them, when project already in ecosystem. But it's up to you. I do not have strong opinion on that. My problem with that was tests were failing a lot. If we fix tests then it's ok to have them on submission, but if they are failing, we need to turn them off to save user form confusion.

**Comment by IceKhan13** [comment]
Tier should be 'Community' by default

**Comment by mickahell** [comment]
> tests were failing a lot and what I thought is to turn off tests on submission. Only run them, when project already in ecosystem. But it's up to you. I do not have strong opinion on that. My problem with that was tests were failing a lot. If we fix tests then it's ok to have them on submission, but if they are failing, we need to turn them off to save user form confusion.

Those last issues we improve a lot the tests make them passed :)
I think we can put this option for disabled tests aside for a moment.
> ~[ ] turn of issue tests~

**Comment by mickahell** [comment]
Hi @IceKhan13 :)

As the future of tiers are discussing in the NFC and tests are being disabled in waiting for what we want for the future of Ecosystem I'm closing the issue, do not hesitate to reopen it you think I'm mistaking ^^'
