### ISSUE TITLE
Move historical results from `members.json` into separate file

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/ecosystem#228]
### What is the expected enhancement?

Move historical results from `members.json` into separate file

**Comment by dhruvshettty** [comment]
Seems like a good first issue to try. 
Do you mean moving the values for the key `tests_results` or `historical_test_results` if values exist under the first nesting level (`Main`, `Community`, `Extensions`, etc)?

**Comment by IceKhan13** [comment]
@dhruvshettty Hey! Thank you for interest in this issue!

I mean remove `historical_test_results` field from `members.json` and move it to separate file. Probably separate file structure will be something like 
```json
{
    "1": {
        "repo_url": ...,
        "historical_test_results": [...]
    }
}
```

**Comment by dhruvshettty** [comment]
@IceKhan13 yes please, I'd like to take this up.

This is the format I'm thinking of:
```
{
    "1": {
              "repo_url": "...",
              "tier": "Community",
              "historical_test_results": [...],
    }
}
```
I'm choosing to keep the `tier` key since that would help us identify the structure of the JSON. And the number is just a unique ID. If this works, I'll get on with it, else please let me know if there are changes required.

**Comment by IceKhan13** [comment]
@dhruvshettty assigned to you! Thank you for jumping on this! You rock! 😄

**Comment by mickahell** [comment]
@AbdullahKazi500 & @dhruvshettty if you are still there maybe you both could sync with @frankharkins and pass on the issue #424 to be clear on the new structure

**Comment by mickahell** [comment]
> Hi I don't get it I am currently working on this @mickahell

Because, the file `members.json` is gonna disapeared to be split into separated individual folder.

**Comment by frankharkins** [comment]
@AbdullahKazi500 what do you have so far? Slack me on the [Qiskit workspace](https://qisk.it/join-slack) (`@frankharkins`) if you prefer.

**Comment by dhruvshettty** [comment]
Hi, sorry I could not work on this. I'm removing myself from this issue, however, @AbdullahKazi500 happy to help you if you need it

**Comment by mickahell** [comment]
Hi @AbdullahKazi500, @frankharkins finished the new structured. You can `pull` the evolve and go ahead :)

> I mean remove `historical_test_results` field from `members.json` and move it to separate file. Probably separate file structure will be something like
> 
> ```json
> {
>     "1": {
>         "repo_url": ...,
>         "historical_test_results": [...]
>     }
> }
> ```

I think you can integrate `historical_test_results` into the new unitary project `toml` file.

Do not hesitate if you have any question

**Comment by frankharkins** [comment]
Gonna close as this seems stale, and I don't think this is needed any more.

With the new structure, having historical test results in the same file is no longer a problem as they can be easily ignored. Separating them out would most likely make the code more complicated. I'm open to other opinions though.
