### ISSUE TITLE
Documentation: contribution guide

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/ecosystem#26]
### What is the expected enhancement?
Improve contribution guide documentation and include all necessary steps for developer to setup env and start developing on ecosystem.

- env setup (pip install requirements)
- how to run tests
- how to perform style checks
- guidance on git (messages, branches, forking etc)

**Comment by mickahell** [comment]
I'm adding what you gave me here :
Run for style checks
```
tox -elint

```
Run for tests
```
tox -epy39
```

`setUp` is called automatically before running tests in test class and `tearDown` is called after. You can use them to create resources for tests and clean them after if you need it.

**Comment by mickahell** [comment]
Other points :
- Add tox.ini template
- Add repo structure example
- Add setup.py template

**Comment by bala-ceg** [comment]
Please assign this issue to me.
