### ISSUE TITLE
[Submission]: Quantum Application Framework - Openshift porting

### ISSUE THREAD

**Issue by vito490** [qiskit-community/ecosystem#266]
### Github repo

https://github.com/vito490/Quantum-Application-Framework.git

### Description

We designed and implemented an architectural framework that aims to standardize the interaction of an existing infrastructure with IBM Quantum, leveraging the most used open source technologies. The general idea is to heavily decouple all the components of the framework and isolate, in a docker container, the components which interact with IBM Quantum. Plus, we focused on automate the provisioning process, so that trying the framework would be as easy as executing a script and in a matter of minutes, all the components will be available on a vanilla OpenShift cluster

### Email

vitosammarco94@gmail.com

### Alternatives

Other framework componets can be found here https://github.com/Quantum-App-Framework

### License

Apache License 2.0

**Comment by IceKhan13** [comment]
cosed in #267
