### ISSUE TITLE
Unclear why test status is listed as failure

### ISSUE THREAD

**Issue by garrison** [qiskit-community/ecosystem#293]
### Steps to reproduce the problem

Look at https://qiskit.org/ecosystem/.

### What is the current behavior?

There are a number of jobs that the page suggests are failing, but when one clicks on the associated Action, it appears to have passed.  For instance, three of the jobs under Quantum Random Access Optimization are red, but after clicking "see test logs", it lists the status as Success.  I've noticed this happens for some other packages too, e.g. pytorch-quantum.

### What is the expected behavior?

Either status should be green, or it should be obvious why a job failed.

**Comment by mickahell** [comment]
Hi @garrison I have a part of the answer :)
When we created the Actions, we wanted the jobs to always succeed to finished in order and then generating a report to push in the issue concerned indicating if the tests passed or failed.

**Comment by mickahell** [comment]
Transform your issue as feature, in order to check how to improve the Actions output

**Comment by mickahell** [comment]
Cover by #487
