### ISSUE TITLE
[Submission]: QiskitOpt.jl

### ISSUE THREAD

**Issue by pedroripper** [qiskit-community/ecosystem#306]
### Github repo

https://github.com/psrenergy/QiskitOpt.jl

### Description

QiskitOpt.jl is a Julia package that exports a JuMP wrapper for qiskit-optimization.
It was developed to be integrated with ToQUBO.jl, where users can provide JuMP models for general optimization problems and have them to be automatically reformulated into QUBO instances and then sent to run VQE and QAOA algorithms on quantum computers.

### Email

pedroxavier@psr-inc.com, pedroripper@psr-inc.com, tiago@psr-inc.com, joaquim@psr-inc.com, dbernalneira@usra.edu

### License

MIT license

### Affiliations

@psrenergy and USRA

### Tags

algorithms

**Comment by javabster** [comment]
hello @pedroripper! You joined the Qiskit Ecosystem a little while ago and I just wanted to check in and let you know of some follow up actions you can take to make the most of joining the program, if you're interested:

💬  Join other Qiskit ecosystem developers in the [Slack channel #qiskit-ecosystem](https://qiskit.slack.com/archives/C04RHE56N93) (if you are not in the Qiskit workspace yet, you can sign up here: https://qisk.it/join-slack)

🧠  Help us define the future of the Qiskit Ecosystem: we recently started an RFC on how the Ecosystem should be structured. It is very draft-y at the moment, but you can subscribe for notifications here [Qiskit/RFCs#42](https://github.com/Qiskit/RFCs/pull/42) to participate in that discussion.

📣  Would you like to showcase your project to the Qiskit community? A couple of things you can do to raise awareness for your project:
 - [write a blog for your project](https://github.com/qiskit-community/ecosystem/wiki/Write-a-Blog-for-your-Project) (reach out to Abby Mitchell via slack or [email](mailto:abby.s.mitchell@ibm.com) if you'd like to be featured on the Qiskit Medium)
- Participate in [Qiskit Demoday](https://github.com/Qiskit/feedback/wiki/Qiskit-DemoDays). (reach out to Luciano Bello via slack or [email](mailto:BEL@zurich.ibm.com) to request a slot to demo your project)

Great having you as a part of the ecosystem!

**Comment by pedroripper** [comment]
Hi @javabster! Thank you for your message.
I've just joined the Slack channel and will talk to my colleagues about it.
We are very interested in submitting a blog post. We should be sending you a message in the next few weeks.
