### ISSUE TITLE
[Submission]: Timeline Debugger for the Qiskit Transpiler

### ISSUE THREAD

**Issue by TheGupta2012** [qiskit-community/ecosystem#310]
### Github repo

https://github.com/TheGupta2012/qiskit-timeline-debugger

### Description
A lightweight jupyter widget to highlight the actions of the qiskit transpiler. Qiskit users can simply replace the call to qiskit's `transpile` function with the `debug` method of a `Debugger` instance. Our widget provides an insight into the various details of the transpiler passes such as **circuit evolution**, **property set changes**, **logs** emitted during transpilation and the **docs of the transpiler passes**. More about the project in [README](https://github.com/TheGupta2012/qiskit-timeline-debugger#qiskit-trebugger--). It was primarily developed during the QAMP Fall '21 under the mentorship of [Kevin Krsulich](https://github.com/kdk).
Major contributors : [Harshit Gupta](https://github.com/TheGupta2012) and [Aboulkhair Foda](https://github.com/EgrettaThula)

### Email

harshit.11235@gmail.com

### License

Apache License 2.0

### Tags

plugin

**Comment by IceKhan13** [comment]
@TheGupta2012 thank you for submission! I saw your presentation during QAMP and it is an amazing project!
