### ISSUE TITLE
circuit knitting toolbox and quantum serverless has "_No response_" as tag

### ISSUE THREAD

**Issue by HuangJunye** [qiskit-community/ecosystem#316]
### Steps to reproduce the problem

Go to https://qiskit.org/ecosystem/, search for "circuit knitting toolbox" or "quantum serverless"

### What is the current behavior?

<img width="668" alt="Screen Shot 2023-02-06 at 15 58 31" src="https://user-images.githubusercontent.com/7631333/217006066-a9cce148-8566-40c9-b171-12a9be5ddbda.png">
<img width="655" alt="Screen Shot 2023-02-06 at 15 58 16" src="https://user-images.githubusercontent.com/7631333/217006078-cb56345d-2008-4819-8420-d8d6890faf4d.png">

### What is the expected behavior?

The tag should be replaced with appropriate tag

**Comment by HuangJunye** [comment]
The `tags` field in [the submission template](https://github.com/qiskit-community/ecosystem/blob/main/.github/ISSUE_TEMPLATE/submission.yml) should be compulsory or when no response is chosen, it should remove the tag on the website.

**Comment by IceKhan13** [comment]
wrong tags fixed in https://github.com/qiskit-community/ecosystem/pull/317/commits/6d6e54ea6f3303985624eeae643591a50794b9be.

For form creating separate issue https://github.com/qiskit-community/ecosystem/issues/319
