### ISSUE TITLE
[Submission]: Diskit Python library for distributed quantum computing

### ISSUE THREAD

**Issue by stephendiadamo** [qiskit-community/ecosystem#322]
### Github repo

https://github.com/Interlin-q/diskit

### Description

Distributed quantum computing is a concept that proposes to connect multiple quantum computers in a network to leverage a collection of more, but physically separated, qubits. In order to perform distributed quantum computing, it is necessary to add the addition of classical communication and entanglement distribution so that the control information from one qubit can be applied to another that is located on another quantum computer. For more details on distributed quantum computing, see this blog post: [Distributed Quantum Computing: A path to large scale quantum computing](https://medium.com/@stephen.diadamo/distributed-quantum-computing-1c5d38a34c50)

In this project, we aim to validate distributed quantum algorithms using Qiskit. Because Qiskit does not yet come with networking features, we embed a "virtual network topology" into large circuits to mimic distributed quantum computing. The idea is to take a monolithic quantum circuit developed in the Qiskit language and distribute the circuit according to an artificially segmented version of a quantum processor. The inputs to the library are a quantum algorithm written monolithically (i.e., in a single circuit) and a topology parameter that represents the artificial segmentation of the single quantum processor.

The algorithm takes these two inputs and remaps the Qiskit circuit to the specified segmentation, adding all necessary steps to perform an equivalent distributed quantum circuit. Our algorithm for achieving this is based on the work: [Distributed Quantum Computing and Network Control for Accelerated VQE](https://ieeexplore.ieee.org/document/9351762). The algorithm output is another Qiskit circuit with the equivalent measurement statistics but with all of the additional logic needed to perform a distributed version.

### Email

stephen.diadamo@gmail.com, anuranan.fifa14@gmail.com 

### Alternatives

Interlin-q: https://github.com/Interlin-q/Interlin-q 

A similar library but uses QuNetSim to simulate the network communication for distributed quantum computing.

### License

Apache License 2.0

### Tags

plugin, circuit, converter

**Comment by 1ucian0** [comment]
[Something went wrong](https://github.com/qiskit-community/ecosystem/actions/runs/4191134122/jobs/7265250452) with the action should create the PR for it:
```
  File "/home/runner/work/ecosystem/ecosystem/ecosystem/manager.py", line 177, in parser_issue
    parsed_result = parse_submission_issue(body)
  File "/home/runner/work/ecosystem/ecosystem/ecosystem/utils/submission_parser.py", line 27, in parse_submission_issue
    alternatives = parse[7]
IndexError: list index out of range
Error: Process completed with exit code 1.
```

I'm taking a look.

**Comment by stephendiadamo** [comment]
Thanks, the library isn't yet set up to integrate right with Qiskit, but we can modify it accordingly depending on if this submission is along the right lines for acceptance.

**Comment by 1ucian0** [comment]
re-triggered by  #334

**Comment by 1ucian0** [comment]
Hello @stephendiadamo ! Here some follow up, in case you are interested:

 * Join other Qiskit ecosystem developers in the [Slack channel #qiskit-ecosystem](https://qiskit.slack.com/archives/C04RHE56N93) (if you are not in the Qiskit workspace yet, you can sign up here: https://qisk.it/join-slack)
  * We just started with a discussion about how are we going to organize the ecosystem space. It is very draft-y at the moment, but you can subscribe for notification here https://github.com/Qiskit/RFCs/pull/42 to participate in that discussion.
  * If you would like to show `diskit` to the Qiskit community, let me know [via slack](https://qiskit.slack.com/archives/D7TKZB9PZ) or [email](bel-at-zurich-dot-ibm-com) and get a slot in the [Qiskit Demoday agenda](https://github.com/Qiskit/feedback/wiki/Qiskit-DemoDays).
  
 Welcome to the Qiskit Ecosystem!
