### ISSUE TITLE
[Submission]: SAT Circuits Synthesis Engine

### ISSUE THREAD

**Issue by ohadlev77** [qiskit-community/ecosystem#338]
### Github repo

https://github.com/ohadlev77/sat-circuits-engine

### Description

A Python-Qiskit-based package that provides capabilities of easily generating, executing and analyzing quantum circuits for satisfiability problems according to user-defined constraints. The circuits being generated by the program are based on Grover's algorithm and its amplitude-amplification generalization.

### Email

ohadlev77@gmail.com

### License

Apache License 2.0

### Tags

algorithms, circuit

**Comment by 1ucian0** [comment]
Hello @ohadlev77 ! Here some follow up, in case you are interested:

 * Join other Qiskit ecosystem developers in the [Slack channel #qiskit-ecosystem](https://qiskit.slack.com/archives/C04RHE56N93) (if you are not in the Qiskit workspace yet, you can sign up here: https://qisk.it/join-slack)
  * We just started with a discussion about how are we going to organize the ecosystem space. It is very draft-y at the moment, but you can subscribe for notification here https://github.com/Qiskit/RFCs/pull/42 to participate in that discussion.
  * If you would like to show `sat-circuits-engine` to the Qiskit community, let me know [via slack](https://qiskit.slack.com/archives/D7TKZB9PZ) or [email](bel-at-zurich-dot-ibm-com) and get a slot in the [Qiskit Demoday agenda](https://github.com/Qiskit/feedback/wiki/Qiskit-DemoDays).
  
 Welcome to the Qiskit Ecosystem!
