### ISSUE TITLE
[Submission]: qiskit-symbolic

### ISSUE THREAD

**Issue by SimoneGasperini** [qiskit-community/ecosystem#348]
### Github repo

https://github.com/SimoneGasperini/qiskit-symbolic

### Description

The `qiskit-symbolic` project is meant to enable the symbolic evaluation of quantum states/operators defined by Qiskit parametric circuits. It's based on sympy as the backend for the manipulation of symbolic expressions.
The original idea for this project goes back to the [qiskit-terra#4751](https://github.com/Qiskit/qiskit-terra/issues/4751) issue, where I recently had a discussion with [jakelishman](https://github.com/jakelishman) who finally proposed me to submit my repo to the Qiskit Ecosystem.

### Email

simone.gasperini4@unibo.it

### License

Apache License 2.0

**Comment by SimoneGasperini** [comment]
Any news about the review process of the submitted project? How does it work? @IceKhan13 @1ucian0

**Comment by IceKhan13** [comment]
Hey @SimoneGasperini ! I apologize for late response, I was on vacation 🌴 Merging

**Comment by SimoneGasperini** [comment]
Sorry to bother... Is it possible to edit the repository description and tags appearing on the [Qiskit Ecosystem](https://qiskit.org/ecosystem/) webpage? Because I already edited the first comment on this thread but changes don't seem to be reflected on the webpage as well.

**Comment by IceKhan13** [comment]
@SimoneGasperini fixed in https://github.com/qiskit-community/ecosystem/pull/371.
All members are stored in `members.json` file. Probably we need to include this in contribution guide, if authors wants to edit information about their package.

**Comment by SimoneGasperini** [comment]
Ok thanks! So the "description" field in the same JSON file can be edited as well, right? Can I do that and submit a pull request?

**Comment by IceKhan13** [comment]
@SimoneGasperini ofc you can submit PR! :) file you want to edit is this https://github.com/qiskit-community/ecosystem/blob/main/ecosystem/resources/members.json. It will change soon, but your change will be there anyway.

> Is it enough to set "skip_tests": false to enable testing?

correct

**Comment by SimoneGasperini** [comment]
@IceKhan13 Ok done! I just submitted a pull request with all the fixes needed. Thanks again for your support!

**Comment by 1ucian0** [comment]
Hello @SimoneGasperini  ! Here some follow up, in case you are interested:

 * Join other Qiskit ecosystem developers in the [Slack channel #qiskit-ecosystem](https://qiskit.slack.com/archives/C04RHE56N93) (if you are not in the Qiskit workspace yet, you can sign up here: https://qisk.it/join-slack)
  * We just started with a discussion about how are we going to organize the ecosystem space. It is very draft-y at the moment, but you can subscribe for notification here https://github.com/Qiskit/RFCs/pull/42 to participate in that discussion.
  * If you would like to show `qiskit-symbolic` to the Qiskit community, let me know [via slack](https://qiskit.slack.com/archives/D7TKZB9PZ) or [email](bel-at-zurich-dot-ibm-com) and get a slot in the [Qiskit Demoday agenda](https://github.com/Qiskit/feedback/wiki/Qiskit-DemoDays).
  
 Welcome to the Qiskit Ecosystem!

**Comment by SimoneGasperini** [comment]
Thank you very much @1ucian0 for all the info!
I just joined the Qiskit Ecosystem channel on Slack and I will contact you there very soon for the Qiskit Demoday 😃
