### ISSUE TITLE
Github: tempalte for python projects

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/ecosystem#36]
### What is the expected behavior?
Create Github template for python projects.

**Comment by mickahell** [comment]
- Add tox.ini template
- Add .pylinrc template
- Add .coveragerc template
- Add setup.py template
- Add qe_config.json template
- Add repo structure example

**Comment by mickahell** [comment]
See : https://github.com/mickahell/qiskit-ecosystem_template

**Comment by mickahell** [comment]
@IceKhan13 so we can closes this issue too ?

**Comment by mickahell** [comment]
Link #86

**Comment by mickahell** [comment]
@IceKhan13 you can close this one too :)

**Comment by IceKhan13** [comment]
Closed in #86
