### ISSUE TITLE
[Submission]: Spinoza - a quantum state simulator implemented in Rust

### ISSUE THREAD

**Issue by smu160** [qiskit-community/ecosystem#366]
### Github repo

https://github.com/smu160/spinoza

### Description

Spinoza is a quantum state simulator (implemented in Rust) that is one of the fastest open-source simulators. Spinoza is implemented using a functional approach. Additionally, Spinoza has a `QuantumCircuit` object-oriented interface, which partially matches Qiskit's interface. Spinoza is capable of running in a myriad of computing environments (e.g., small workstations), and on various architectures. At this juncture, Spinoza only utilizes a single thread; however, it is designed to be easily extended into a parallel version, as well as a distributed version. The paper associated with Spinoza is available [here](https://arxiv.org/pdf/2303.01493.pdf).

### Email

sy2685@columbia.edu

### Alternatives

https://github.com/qulacs/qulacs

### License

Apache License 2.0

### Tags

simulation

**Comment by 1ucian0** [comment]
hello @smu160 ! Here some follow up actions, in case you are interested
 * Join other Qiskit ecosystem developers in the [Slack channel #qiskit-ecosystem](https://qiskit.slack.com/archives/C04RHE56N93) (if you are not in the Qiskit workspace yet, you can sign up here: https://qisk.it/join-slack)
  * We just started with a discussion about how are we going to organize the ecosystem space. It is very draft-y at the moment, but you can subscribe for notification here https://github.com/Qiskit/RFCs/pull/42 to participate in that discussion.
  * If you would like to show `qulacs` to the Qiskit community, let me know [via slack](https://qiskit.slack.com/archives/D7TKZB9PZ) or [email](bel-at-zurich-dot-ibm-com) and get a slot in the [Qiskit Demoday agenda](https://github.com/Qiskit/feedback/wiki/Qiskit-DemoDays).
  
 Welcome to the Qiskit Ecosystem!
