### ISSUE TITLE
Extend members DB with optional website field

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-community/ecosystem#369]
### What is the expected enhancement?

We need to extend ecosystem database with a "website" field. After this, the `q.o/ecosystem`'s tails need to be extended with it. The field should be optional.

- [ ] Extend the DB in the code
- [ ] Extend the issue template
- [ ] Test

**Comment by mickahell** [comment]
Doesn't this one has been done by #413 #418 #419 ? @frankharkins

**Comment by mickahell** [comment]
Done in https://github.com/qiskit-community/ecosystem/pull/413 https://github.com/qiskit-community/ecosystem/pull/418 https://github.com/qiskit-community/ecosystem/pull/419
