### ISSUE TITLE
[Submission]: Variational Quantum Linear Solver

### ISSUE THREAD

**Issue by NicoRenaud** [qiskit-community/ecosystem#372]
### Github repo

https://github.com/QuantumApplicationLab/vqls-prototype

### Description

Dear qiskit developers,

we have developed a prototype for the variational quantum linear solver. We've used the qiskit prototype-template and did our best to follow qiskit coding standards. We are still having a few issues with pylint and mypy and had to disable some error for the tests to pass for now. The solver uses the Estimator/Sampler primitives and can be run through runtime seamlessly. 

We would love to share our work with the qiskit community and make the prototype available to a broader audience. We would therefore like to know if you would be interested in this prototype. If you are, we could review the code together and include vqls prototype as part of the qiskit-community.

Thanks for all the work you are doing for the community !

Nico
  

### Email

nicolas.gm.renaud@gmail.com

### Alternatives

The prototype builds on the qiskit-textbook chapter and tutorial. The prototype allows to use the primitives and use different cost function and test circuits to optimize the parameters.  

### License

Apache License 2.0

### Affiliations

Netherlands eScience Center @ Quantum Application Lab, Amsterdam NL

**Comment by 1ucian0** [comment]
hello @NicoRenaud ! Here some follow up actions, in case you are interested
 * Join other Qiskit ecosystem developers in the [Slack channel #qiskit-ecosystem](https://qiskit.slack.com/archives/C04RHE56N93) (if you are not in the Qiskit workspace yet, you can sign up here: https://qisk.it/join-slack)
  * We just started with a discussion about how are we going to organize the ecosystem space. It is very draft-y at the moment, but you can subscribe for notification here https://github.com/Qiskit/RFCs/pull/42 to participate in that discussion.
  * If you would like to show `vqls-prototype` to the Qiskit community? Let me know [via slack](https://qiskit.slack.com/archives/D7TKZB9PZ) or [email](bel-at-zurich-dot-ibm-com) and get a slot in the [Qiskit Demoday agenda](https://github.com/Qiskit/feedback/wiki/Qiskit-DemoDays).
  
 Welcome to the Qiskit Ecosystem!
