### ISSUE TITLE
[Submission]: Quantum-enhanced variational autoencoder

### ISSUE THREAD

**Issue by Anantha-Rao12** [qiskit-community/ecosystem#387]
### Github repo

https://github.com/Anantha-Rao12/Quantum-enhanced-variational-autoencoder

### Description

- This is a submission for the Qiskit Ecosystem.
- The project is the source code for building and running a hybrid quantum-classical neural network for generative modeling. 
- The code is a qiskit implementation of a quantum-enhanced variational autoencoder (QeVAE). 
- The project is based on the research paper "Learning hard distributions with quantum-enhanced Variational Autoencoders" by Rao et al. (https://arxiv.org/abs/2305.01592).

### Email

anantharao@zohomail.in

### Alternatives

There are no alternatives to the project!

### License

Apache License 2.0

### Affiliations

Indian Institute of Science Education and Research
IBM Research India

### Tags

paper implementation

**Comment by mickahell** [comment]
See #436
