### ISSUE TITLE
[Submission]: qBraid-SDK

### ISSUE THREAD

**Issue by ryanhill1** [qiskit-community/ecosystem#397]
### Github repo

https://github.com/qBraid/qBraid

### Description

The qBraid-SDK is a Python toolkit for cross-framework abstraction, transpilation, and execution of quantum programs.

### Email

ryanhill@qbraid.com

### Alternatives

There are some alternatives to individual modules within the qBraid-SDK e.g. to execute a Qiskit circuit on an AWS device, you could use the `qiskit-braket-provider`. However, there aren't any other existing projects that support the same matrix of quantum program types and backends through a single, unified interface.

### License

GNU General Public License (GPL)

### Affiliations

qBraid Co.

### Tags

circuit, openqasm, converter

**Comment by ryanhill1** [comment]
Hi @1ucian0 @IceKhan13, I've added the [`ecosystem.json`](https://github.com/qBraid/qBraid/blob/ecfda9c741e1c2022e69136b24ac4f3016d47484/ecosystem.json) file to the qBraid-SDK repository following the linked instructions. However, it seems the integration test(s) are "failing" with the following [logs message](https://github.com/qiskit-community/ecosystem/actions/runs/5284224138/jobs/9561428783#step:12:1):

> **Warning**: Unexpected input(s) 'repository', valid inputs are ['token', 'path', 'add-paths', 'commit-message', 'committer', 'author', 'signoff', 'branch', 'delete-branch', 'branch-suffix', 'base', 'push-to-fork', 'title', 'body', 'labels', 'assignees', 'reviewers', 'team-reviewers', 'milestone', 'draft']

I'm not exactly sure what my next steps should be. Any guidance would be much appreciated! Thanks.

Note: I opened a separate issue/PR a few weeks ago, but did not have the required ecosystem file yet. After adding it, I wasn't sure how to re-run the tests, so I closed the old issue and opened a new one. Hopefully that clears any confusion.

**Comment by IceKhan13** [comment]
Hey @ryanhill1 ! 
Thank you for submission!
Regarding warning: we will look into it. Thank you for pointing on it. 
Next steps will be tests and review. We will let you know in connected PR if you something else is needed from your side.

Thank you again!

**Comment by ryanhill1** [comment]
@IceKhan13 Great, thank you!

**Comment by mickahell** [comment]
see #440
