### ISSUE TITLE
[DEPRECIATION] Can't `set-output` to share information between steps in CI

### ISSUE THREAD

**Issue by mickahell** [qiskit-community/ecosystem#406]
### Steps to reproduce the problem
Launch a submission

⚠️ 
```Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/```

### What is the current behavior?
The `set-output` feature of GitHub Actions _soon_ gonna be depreciated and so we need to change our way to pass informations through steps in our CI.

### What is the expected behavior?
Using another to pass informations between steps

**Comment by frankharkins** [comment]
I think a neat solution could be to just pass the project name to each function, then read from the TOML file. Should be able to cut down things like this
https://github.com/qiskit-community/ecosystem/blob/c1c0b5623054fcd8845d75aac862eeddb8d2cb66/.github/workflows/ecosystem-batch-repo-check.yml#L49-L54
To something like
```sh
python manager.py dispatch_check_workflow \
    --repo_url=${repositories[$i]} \
    --token=${{ secrets.WORKFLOW_DISPATCH_PAT }} \
```

**Comment by mickahell** [comment]
It come from our way to pass variable from a step to another. We did that because that was the way to do it 2 years ago, it probably have another way to do it now.

For me it's a purely Actions problem and not relative to python at all. Or did I miss something @frankharkins ?
