### ISSUE TITLE
Autom `batch_check_` branch merged

### ISSUE THREAD

**Issue by mickahell** [qiskit-community/ecosystem#425]
### What is the expected enhancement?

We have a lot of `batch_check_` branch in waiting to be merge, we need to find a way to not have to approved them manually.

**Comment by mickahell** [comment]
@frankharkins do you have an idea of what we could do to avoid the actual situation of having lot of state branches ?

At the beginning with Iskandar, we did that in order to _control_ the modification into `main` but maybe now we could automatize the PR merging with basic check (like code conflict or something like) ? What do you thing ?

**Comment by frankharkins** [comment]
Maybe just deleting the branch after merging? I think there's a GitHub setting we can enable

**Comment by mickahell** [comment]
I was more thinking having something like that for those branches : https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request

Or using an Actions like that : https://github.com/marketplace/actions/merge-pull-requests-automerge-action

**Comment by frankharkins** [comment]
I think we should still review each PR as they're still a bit unreliable. For example, https://github.com/qiskit-community/ecosystem/pull/471 had some problems (probably due to requests). Shall I enable auto-merging and automatic branch deletion?

**Comment by frankharkins** [comment]
FYI I've deleted all the unused `branch_check_*` and `submission_*` branches.

**Comment by mickahell** [comment]
> I think we should still review each PR as they're still a bit unreliable. For example, #471 had some problems (probably due to requests). Shall I enable auto-merging and automatic branch deletion?

Indeed :/
In any case before enabling auto merging, we should setup some check like conflict check, lint toml, ... but yes for fields values check I don't really know what we can do to prevent bug like the one you notified.

Today you are here to maintains the project but later does it always gonna be someone for maintains the PR merging regularly ?

**Comment by mickahell** [comment]
Closes this as the Action gonna evolve and so those branchs not gonna exist anymore or in another form
