### ISSUE TITLE
[Submission]: Quantum-enhanced variational autoencoder

### ISSUE THREAD

**Issue by mickahell** [qiskit-community/ecosystem#436]
### Github repo

https://github.com/Anantha-Rao12/Quantum-enhanced-variational-autoencoder

### Description

- This is a submission for the Qiskit Ecosystem.
- The project is the source code for building and running a hybrid quantum-classical neural network for generative modeling.
- The code is a qiskit implementation of a quantum-enhanced variational autoencoder (QeVAE).
- The project is based on the research paper "Learning hard distributions with quantum-enhanced Variational Autoencoders" by Rao et al. (https://arxiv.org/abs/2305.01592).

### Email

anantharao@zohomail.in

### License

Apache License 2.0

### Affiliations

Indian Institute of Science Education and Research
IBM Research India

### Labels

paper implementation

### Website

https://anantha-rao12.github.io

**Comment by mickahell** [comment]
Hi @Anantha-Rao12 :) I re-created your issue du to breaking change on our sides.

You have a problem with your dependancies as some are install from local sources.

**Comment by Anantha-Rao12** [comment]
Hi @mickahell 
Thanks for reviewing the submission. Please can you let me know what modifications I need to make. 
I do not have a `tests` folder, and I am not sure if that's the problem. How do I know which dependencies are causing the issues? 

Thanks.

**Comment by mickahell** [comment]
For example this one : ﻿`anyio @ file:///D:/bld/anyio_1614388928330/work/dist`
Ecosystem can't install it as it's only available in your local computer.

And it seems you have a lot of requirements, maybe you don't need to have all of them to make your program works.

What I suggest you is to check this repo : https://github.com/mickahell/qiskit-ecosystem_template/tree/main
(it's a template repo for create simple project with minimal needs for the Ecosystem) and get the `.github/workflows` and the `tox.ini` and adapt them for your case. It allow to test the installation of your project inside the GitHub Action (almost) same as we do here.

**Comment by Anantha-Rao12** [comment]
I have cleaned up the `requirements.txt` and added both `.github/workflows` and `tox.ini`. I have modified these files for my submission. Is there anything I am missing?
Also, can you add my website to the info section? 
`website : "https://anantha-rao12.github.io/" `

**Comment by mickahell** [comment]
You need to adapt the tox to the structure of your projetc, do not hesitate to delete what you don't need

**Comment by mickahell** [comment]
You'll also need a `tests`. Just try to add a basic set of tests.

**Comment by mickahell** [comment]
As couple of things changed in the issue template. I'm closing this issue and let you create a new one with my suggestion above taken :)
