### ISSUE TITLE
[Submission]: Qiskit-Shots-Animator

### ISSUE THREAD

**Issue by mickahell** [qiskit-community/ecosystem#438]
### Github repo

https://github.com/teavuihuang/qiskit-shots-animator

### Description

[Qiskit-Shots-Animator ](https://pypi.org/project/qiskit-shots-animator/1.0.1/)is an open-source Python add-on package I developed for IBM Qiskit that animates quantum job execution results e.g. for 1024 shots: "{'000': 510, '111': 514}" as microwave flashes either on a gate map, or x-ray photo of the quantum computer chip. The stand-alone looping GIF animation can be viewed directly in the Jupyter notebook or saved & exported to webpages & social media. Qiskit animation examples can be seen in the [Github repo](https://github.com/teavuihuang/qiskit-shots-animator).

It's purpose is to help newcomers to Quantum to visually comprehend the quantum results. It can also be used as a fun, indirect way to learn quantum circuit design as the students modify the circuits to draw and create simple animation patterns on the gate map like a LED signboard. Hence, I think this is something that could be used / incorporated in IBM Qiskit tutorials, lessons and even YouTube video lessons and presentations.

### Email

TVHUANG@HOTMAIL.COM

### License

Apache License 2.0

### Labels

simulation, circuit simulator, circuit, game, notebook

**Comment by mickahell** [comment]
Hi @teavuihuang :) I re-created your issue du to breaking change on our sides.

As your repo is not structured as what our program are expected, you have to add a file at the root of your repo call `ecosystem.json` see here : https://github.com/qiskit-community/ecosystem/blob/main/docs/project_overview.md#adding-project-to-the-ecosystem

**Comment by mickahell** [comment]
Hi @teavuihuang any news :) ?

**Comment by teavuihuang** [comment]
> Hi @teavuihuang any news :) ?

Hi! Sorry I don't have time to fix this at the moment :(

**Comment by mickahell** [comment]
As form our side the code of the submission has evolved and labels changed.

If it's ok for you I'll close this issue and I let you create a new one later :)
