### ISSUE TITLE
Submission: Prepare 2 projects candidate

### ISSUE THREAD

**Issue by mickahell** [qiskit-community/ecosystem#44]
### What is the expected
We need to have 2 projects ready to be add in the ecosystem. 
Can be our own project or from other advocates

### Requirements
- using qiskit
- be compatible qiskit latest and qiskit dev (master branch)
- having unit tests (>80% coverage)
- having a well linter (could use black) 

Epic #9

**Comment by mickahell** [comment]
@IceKhan13 could you add some labels please 😄

**Comment by IceKhan13** [comment]
Candidates:
- https://github.com/q-optimize/c3
- https://github.com/HuangJunye/QPong

**Comment by mickahell** [comment]
> * https://github.com/SupertechLabs/qiskit-superstaq - no requirements.txt

It looks to have one : https://github.com/SupertechLabs/qiskit-superstaq/blob/main/requirements.txt

**Comment by IceKhan13** [comment]
closed in #92
