### ISSUE TITLE
[BUG] Unable to process Output

### ISSUE THREAD

**Issue by mickahell** [qiskit-community/ecosystem#458]
### Steps to reproduce the problem
The output evolution seems to have import a new bug when an error occur during check: 
see : https://stackoverflow.com/questions/74137120/how-to-fix-or-avoid-error-unable-to-process-file-command-output-successfully

This problem only occur with project who has an error during their check and so in anycase need to adapt for passing our check. The problem does not occur with passing project.

**Comment by mickahell** [comment]
Check run : https://github.com/mickahell/ecosystem/actions/runs/5674293890/job/15377949993

**Comment by mickahell** [comment]
@frankharkins seems we introduce a new bug for dev test. When we have a fail log the output also make the entire job faile.
I'm not sure that come from GitHub, maybe from the python too

**Comment by frankharkins** [comment]
Is it possible this is related to https://github.com/qiskit-community/ecosystem/pull/457?

**Comment by mickahell** [comment]
> Is it possible this is related to #457? Or is it most likely #443?

About #457 I don't really think, you mainly just refacto the class syntax and didn't touch the logic. But yes I think it's because the output is not entirely simple text or it's maybe too long (#443 related).

**Comment by minwook-shin** [comment]
@mickahell 
For your reference,
https://github.com/qiskit-community/ecosystem/actions/runs/5689083697/job/15419969451
looks similar to submitted ecosystem #462 CI/CD error. 

thank you for maintaining the Qiskit ecosystem.

**Comment by mickahell** [comment]
Hi @minwook-shin :)
Thanks I find why and fixed it in PR yesterday night ;)

Your submission have an error, let's discuss about it in your submission issue
