### ISSUE TITLE
[Submission]: 

### ISSUE THREAD

**Issue by Jayshah25** [qiskit-community/ecosystem#475]
### Github repo

https://github.com/Jayshah25/Quantum-Glasses

### Description

Visualize effect of Quantum Gates on a single qubit via Bloch Sphere Simulation!

### Email

shahj097@gmail.com

### Alternatives

The only alternative is to code up a circuit (qiskit.QuantumCircuit) and then use visualize_transition from qiskit.visualization. Quantum Glasses implementation wraps all of this into a simple beginner-friendly Tkinter Software.

### License

Apache License 2.0

**Comment by mickahell** [comment]
> The tag for this project could be "quantum software" since this is a tkinter implementation.

Hi @Jayshah25 :)
Can you redo your submission with full information please :
- you need to add a name in the issue title
- add your tag from the list (if you don't find something, that correspond please tell us)
Software is to much generic, indeed every member of the ecosystem is a software. Maybe plugin or widget could be more appropriate ?

Also you need to have at least one test to be able to pass the check, also can you add a `requirements.txt` file with the python dependencies ?

**Comment by Jayshah25** [comment]
ok, I will redo the submission while keeping all these points in mind. And maybe widget tag is indeed appropriate.

**Comment by frankharkins** [comment]
I think `visualization` or `game` tag is most appropriate. There is at least one other project that would fit a `visualization` so I'm in favour of adding it.

**Comment by Jayshah25** [comment]
I feel "visualization" fits better than "game". I have opened the new submission issue here: https://github.com/qiskit-community/ecosystem/issues/478
