### ISSUE TITLE
[Submission]: Quantum Glasses

### ISSUE THREAD

**Issue by Jayshah25** [qiskit-community/ecosystem#478]
### Github repo

https://github.com/Jayshah25/Quantum-Glasses

### Description

Visualise the effects of Single Qubit Gates on a Qubit via Bloch Sphere Simulation in a Tkinter Software.

### Email

shahj097@gmail.com

### Alternatives

The only alternative is to code up a circuit (qiskit.QuantumCircuit) and pass the circuit to visualize_transition from qiskit.visualization. Quantum Glasses implementation wraps all of this into a simple, easy to use Tkinter Software.

### License

Apache License 2.0

### Tags

visualization

**Comment by mickahell** [comment]
The problem seems to be your requirements, you don't need most of them.

From your program file, you only need :
- qiskit
- qiskit[visualization]
- numpy
- tkinter
- pytest

Your test is not a test class, here an example of a simple test : https://github.com/mickahell/qiskit-ecosystem_template/blob/main/tests/test_random.py

**Comment by Jayshah25** [comment]
Most of the other packages are dependencies of qiskit

**Comment by mickahell** [comment]
> Most of the other packages are dependencies of qiskit. I have updated the tests with test class

Pip know how to deal with dependencies, just add the strict minimum.

**Comment by Jayshah25** [comment]
`contourpy==1.1.0        # matplotlib dependency, not required for project
cycler==0.11.0
dill==0.3.7  
exceptiongroup==1.1.2   # for pytest
fonttools==4.42.0       # matplotlib dependency, not required for project  
iniconfig==2.0.0        # for pytest
kiwisolver==1.4.4
matplotlib==3.7.2
mpmath==1.3.0
numpy==1.25.2
packaging==23.1
Pillow==10.0.0
pluggy==1.2.0          # for pytest
ply==3.11
psutil==5.9.5
pyparsing==3.0.9
pytest==7.4.0
python-dateutil==2.8.2
qiskit==0.44.0
qiskit-terra==0.25.0
rustworkx==0.13.1
six==1.16.0
stevedore==5.1.0
sympy==1.12
typing_extensions==4.7.1
`

I have tried to remove everything unnecessary. The three modules "exceptiongroup", "iniconfig" and "pluggy" are only required for pytest. The other two modules "contourpy" and "fonttools" are not required for the project but are dependencies of the matplotlib. 

All the other modules that seem insignificant are required for a successful run. I have manually checked it.

**Comment by mickahell** [comment]
You can do even better ;)

What you don't need :
- ~qiskit-terra~ part of qiskit package 
- ~python-dateutil~ part of python
- ~rustworkx~ part of qiskit
- ...

More generally, if you don't need to import it in your program you don't need to install it.
![image](https://github.com/qiskit-community/ecosystem/assets/20951376/e8ba8931-99fd-403c-9351-ffd1ce321f55)
So in your program you are using, qiskit, qiskit[visualization], numpy, tkinter and pytest.

During the pip setup of those packages, pip will handle by himself the dependencies they need and their version. You can trust him :) (else your program could not be able to works correctly on different OS and python env).

If you want to check what I'm saying you can setup automatic testing with github Actions and using tox (look at this repo : [qiskit-ecosystem_template](https://github.com/mickahell/qiskit-ecosystem_template) )

**Comment by Jayshah25** [comment]
All those packages rustworkx, cycler etc are required for the visualize_transition function.

**Comment by Jayshah25** [comment]
So, I need to add `ecosystem.json` to the project, right?

**Comment by mickahell** [comment]
@Jayshah25 I created you a PR with everything you need https://github.com/Jayshah25/Quantum-Glasses/pull/1

**Comment by Jayshah25** [comment]
Thank you for the PR. I have merged it with the main branch.

**Comment by 1ucian0** [comment]
Hello @Jayshah25! You joined the Qiskit Ecosystem a little while ago and I just wanted to check in and let you know of some follow up actions you can take to make the most of joining the program, if you're interested:

💬  Join other Qiskit ecosystem developers in the [Slack channel #qiskit-ecosystem](https://qiskit.slack.com/archives/C04RHE56N93) (if you are not in the Qiskit workspace yet, you can sign up here: https://qisk.it/join-slack)

🧠  Help us define the future of the Qiskit Ecosystem: we recently started an RFC on how the Ecosystem should be structured. It is very draft-y at the moment, but you can subscribe for notifications here [Qiskit/RFCs#46](https://github.com/Qiskit/RFCs/pull/46) to participate in that discussion.

📣  Would you like to showcase your project to the Qiskit community? A couple of things you can do to raise awareness for your project:
 - [write a blog for your project](https://github.com/qiskit-community/ecosystem/wiki/Write-a-Blog-for-your-Project) (reach out to Abby Mitchell via slack or [email](mailto:abby.s.mitchell@ibm.com) if you'd like to be featured on the Qiskit Medium)
- Participate in [Qiskit Demoday](https://github.com/Qiskit/feedback/wiki/Qiskit-DemoDays). (reach out to Luciano Bello via slack or [email](mailto:BEL@zurich.ibm.com) to request a slot to demo your project)

Great having you as a part of the ecosystem!
