### ISSUE TITLE
Add label to issue and PR during submission wf and improve output

### ISSUE THREAD

**Issue by mickahell** [qiskit-community/ecosystem#480]
### What is the expected enhancement?

 Add labels :
- `submission` label to every submission issue and PR
- `on hold` label to every submission issue and PR who doesn't pass the standard check
- `ready` label to every submission issue and PR who passed the standard check

Improve output message.

**Comment by mickahell** [comment]
@frankharkins could you create the label `ready` for submission ready to be merged (or something similar) please :)

**Comment by frankharkins** [comment]
Done :)
