### ISSUE TITLE
[Submission]: Qiskit Algorithms

### ISSUE THREAD

**Issue by ElePT** [qiskit-community/ecosystem#484]
### Github repo

https://github.com/qiskit-community/qiskit-algorithms

### Description

Qiskit Algorithms is a library of quantum algorithms based on Qiskit, suitable to run on near-term quantum devices with short-depth circuits.

### Email

ept@zurich.ibm.com

### License

Apache License 2.0

### Affiliations

IBM Quantum

### Labels

Algorithms

### Website

https://qiskit.org/ecosystem/algorithms

**Comment by mickahell** [comment]
Hi @ElePT :)

It seems to have a problem with finding the `ddt` python module, error :
`ModuleNotFoundError: No module named 'ddt'`

**Comment by mickahell** [comment]
> Hey @mickahell, I was wondering where did you find these error logs pointing to ddt, I cannot find them (also not sure why would that fail when it's correctly specified in `requirements.txt`)

I think I find out why, by default we only install the `requirements.txt` and not the `requirements-dev.txt` and `ddt` is in your `-dev.txt` and not in the regular one.
Could you add an `ecosystem.json` file to your project, something like that should do the job :

```json
{
    "dependencies_files": [
        "requirements.txt",
        "requirements-dev.txt"
    ],
    "extra_dependencies": [
        "pytest"
    ],
    "language": {
        "name": "python",
        "versions": ["3.9"]
    },
    "tests_command": [
        "pytest"
    ],
    "styles_check_command": [
        "pylint -rn qiskit_algorithms tests"
    ],
    "coverages_check_command": [
        "coverage3 run -m pytest",
        "coverage3 report --fail-under=80"
    ]
}
```

**Comment by mickahell** [comment]
Hi @ElePT any news :)
