### ISSUE TITLE
[Submission]: Optimal Pauli string grouping for dense operators

### ISSUE THREAD

**Issue by atlytle** [qiskit-community/ecosystem#488]
### Github repo

https://github.com/atlytle/dense-ev

### Description

Implements expectation value measurements in Qiskit using optimal dense grouping. Dense-ev provides an improvement of ~2^m over naive grouping and (3/2)^m over qubit-wise commuting groups. Based on arXiv:2305.11847.

### Email

atlytle@gmail.com 

### License

Apache License 2.0

### Affiliations

University of Illinois at Urbana-Champaign

### Tags

paper implementation

### Website

https://github.com/atlytle/dense-ev

**Comment by mickahell** [comment]
Awesome 🚀

**Comment by mickahell** [comment]
@atlytle seems your last commit make the tests doesn"t pass anymore :/

**Comment by atlytle** [comment]
I had expanded the test coverage slightly, locally it runs ok with tox and unittest. I changed the function name to check_random_H(m) in case there is something automatic with functions "test*()". Do you have any suggestions? Thanks!

**Comment by mickahell** [comment]
@atlytle never mind
I just did a test run, and it seems to passed --> run log : https://github.com/mickahell/ecosystem/actions/runs/5882471443/job/15953060710
Maybe that was just a network problem or something like.

Can you just do an edit in your issue and modify a space or a dot and save, that'll launch the wf again :)

**Comment by 1ucian0** [comment]
hello @atlytle! You joined the Qiskit Ecosystem a little while ago and I just wanted to check in and let you know of some follow up actions you can take to make the most of joining the program, if you're interested:

💬  Join other Qiskit ecosystem developers in the [Slack channel #qiskit-ecosystem](https://qiskit.slack.com/archives/C04RHE56N93) (if you are not in the Qiskit workspace yet, you can sign up here: https://qisk.it/join-slack)

🧠  Help us define the future of the Qiskit Ecosystem: we recently started an RFC on how the Ecosystem should be structured. It is very draft-y at the moment, but you can subscribe for notifications here [Qiskit/RFCs#42](https://github.com/Qiskit/RFCs/pull/42) to participate in that discussion.

📣  Would you like to showcase your project to the Qiskit community? A couple of things you can do to raise awareness for your project:
 - [write a blog for your project](https://github.com/qiskit-community/ecosystem/wiki/Write-a-Blog-for-your-Project) (reach out to Abby Mitchell via slack or [email](mailto:abby.s.mitchell@ibm.com) if you'd like to be featured on the Qiskit Medium)
- Participate in [Qiskit Demoday](https://github.com/Qiskit/feedback/wiki/Qiskit-DemoDays). (reach out to Luciano Bello via slack or [email](mailto:BEL@zurich.ibm.com) to request a slot to demo your project)

Great having you as a part of the ecosystem!

**Comment by atlytle** [comment]
Thank you, @1ucian0!
