### ISSUE TITLE
Tests: Add workflows CI tests

### ISSUE THREAD

**Issue by mickahell** [qiskit-community/ecosystem#50]
### What is the expected enhancement?

Add workflows tests with [act](https://github.com/nektos/act) cmd inside the [actual tests, lint, black, ... CI](https://github.com/qiskit-community/ecosystem/blob/main/.github/workflows/tests.yml) :
- [ ] Adapt workflows
- [ ] Adapt payload
- [ ] Adapt env
- [ ] Launch cmd `tox -eci`

**Comment by IceKhan13** [comment]
Closing as not needed for now
