### ISSUE TITLE
Some `check_project` actions are failing

### ISSUE THREAD

**Issue by frankharkins** [qiskit-community/ecosystem#502]
### What is the current behavior?

These action runs have failed:
- https://github.com/qiskit-community/ecosystem/actions/runs/5924785194/job/16062982146#step:7:80
- https://github.com/qiskit-community/ecosystem/actions/runs/5924783399/job/16062976600#step:6:80
- https://github.com/qiskit-community/ecosystem/actions/runs/5924781948/job/16062972378#step:6:80

### What is the expected behavior?

Action runs correctly

### Any ideas?

Earlier error code is 128, which is probably Git's "git did not exit cleanly". This may just be something that happens every now and again; we should keep an eye out to see if the same repos fail next time, and maybe re-try failed jobs once.

**Comment by mickahell** [comment]
2 of the three are because the repo moved and so the link is 404 now.
The other one, is just a network problem, already happen and rerun it make it pass

**Comment by mickahell** [comment]
dense-ev is passed in the scheduled check_project of this morning
