### ISSUE TITLE
Not need to use `qiskit-terra`in dev tests anymore

### ISSUE THREAD

**Issue by mickahell** [qiskit-community/ecosystem#510]
### What is the expected enhancement?

With qiskit-terra being renamed qiskit we can clean some code.
Delete the `package` var in tox tpl in order to let `qiskit` hard coded.

**Comment by shobhit9957** [comment]
I would love to contribute.. can you please provide some more information....

**Comment by mickahell** [comment]
Hi @shobhit9957 :) sure

In the tox template we have this var `package_to_check` :
https://github.com/qiskit-community/ecosystem/blob/ba07fa38607a9b53aecd328977fa7e7ca0f7f4c1/ecosystem/templates/configured_tox.ini#L27

This var was using for get back the version of `qiskit-terra` but it been renamed `qiskit`, so we don't need this var and so just hardcoded `qiskit` will do the job :)

Also if it can help you the start of this var to generate this file is in the file `ecosystem/manager.py` in each `python_*_tests` function. And so the goal is to delete this var entirely.
