### ISSUE TITLE
[Submission]: Add Subspace Search Variational Quantum Eigensolver (SSVQE)

### ISSUE THREAD

**Issue by JoelHBierman** [qiskit-community/ecosystem#515]
### Github repo

https://github.com/JoelHBierman/SSVQE

### Description

The SSVQE algorithm (https://arxiv.org/abs/1810.09434) is a generalization of VQE to find low-lying eigenstates of a Hermitian operator. This specific implementation of SSVQE carries out one optimization procedure using weights.

### Email

joel.bierman@duke.edu

### License

Apache License 2.0

### Affiliations

Duke University

### Labels

Algorithms, Chemistry

**Comment by mickahell** [comment]
Hi @JoelHBierman :)

Can you plain text your description please

**Comment by frankharkins** [comment]
Also, @JoelHBierman can you try to keep the description ~30 words? For example:

> The SSVQE algorithm (https://arxiv.org/abs/1810.09434) is a generalization of VQE to find low-lying eigenstates of a Hermitian operator. This specific implementation of SSVQE carries out one optimization procedure using weights.

This description is just for the [qiskit.org/ecosystem](https://qiskit.org/ecosystem) web page, where users will work out if the project is what they're looking for. They'll click through to your repo for more details on how it works.

**Comment by JoelHBierman** [comment]
I see, yes I'll shorten the description and move the rest to the README.

**Comment by mickahell** [comment]
Hi @JoelHBierman 
Can you add the `ecosystem.json` file at the root of your repo with something like that :
```json
{
    "dependencies_files": [
        "requirements.txt",
        "requirements-dev.txt"
    ],
    "extra_dependencies": [
        "pytest"
    ],
    "language": {
        "name": "python",
        "versions": ["3.9"]
    },
    "tests_command": [
        "pytest"
    ],
    "styles_check_command": [
        "pylint -rn ssvqe test"
    ],
    "coverages_check_command": [
        "coverage3 run -m pytest",
        "coverage3 report --fail-under=80"
    ]
}
```

**Comment by JoelHBierman** [comment]
Yes I'll work on that and add it shortly.

**Comment by JoelHBierman** [comment]
I have added this file along with the other files from the ecosystem template that were missing.

**Comment by JoelHBierman** [comment]
Can some of the settings in .pylintrc be customized or are these strict standards that all packages in the community repo must adhere to?

**Comment by mickahell** [comment]
> Can some of the settings in .pylintrc be customized or are these strict standards that all packages in the community repo must adhere to? Using the defaults, I do not think this package would pass the linting tests without some extensive re-writing with regards to the number of class attributes, variables, ect...

We do not check the lint anymore, maybe one day we will but today we are not :)

**Comment by 1ucian0** [comment]
hello @JoelHBierman! You joined the Qiskit Ecosystem a little while ago and I just wanted to check in and let you know of some follow up actions you can take to make the most of joining the program, if you're interested:

💬  Join other Qiskit ecosystem developers in the [Slack channel #qiskit-ecosystem](https://qiskit.slack.com/archives/C04RHE56N93) (if you are not in the Qiskit workspace yet, you can sign up here: https://qisk.it/join-slack)

🧠  Help us define the future of the Qiskit Ecosystem: we recently started an RFC on how the Ecosystem should be structured. It is very draft-y at the moment, but you can subscribe for notifications here [Qiskit/RFCs#42](https://github.com/Qiskit/RFCs/pull/42) to participate in that discussion.

📣  Would you like to showcase your project to the Qiskit community? A couple of things you can do to raise awareness for your project:
 - [write a blog for your project](https://github.com/qiskit-community/ecosystem/wiki/Write-a-Blog-for-your-Project) (reach out to Abby Mitchell via slack or [email](mailto:abby.s.mitchell@ibm.com) if you'd like to be featured on the Qiskit Medium)
- Participate in [Qiskit Demoday](https://github.com/Qiskit/feedback/wiki/Qiskit-DemoDays). (reach out to Luciano Bello via slack or [email](mailto:BEL@zurich.ibm.com) to request a slot to demo your project)

Great having you as a part of the ecosystem!
