### ISSUE TITLE
Submission workflow is broken

### ISSUE THREAD

**Issue by frankharkins** [qiskit-community/ecosystem#518]
See https://github.com/qiskit-community/ecosystem/actions/runs/6026058555, probably related to #468. I will see if there's an easy fix, otherwise I'll just revert #468.

**Comment by mickahell** [comment]
I found why.
In `ecosystem/daos/dao.py` the behaviour of `get_by_url` changed :

- Before, if the url is not find in the db the function return `None` :
```python
    def get_by_url(self, url: str, tier: str) -> Optional[Repository]:
        """Returns repository by URL.

        Args:
            tier: tier of the repo (MAIN, COMMUNITY, ...)

        Return: Repository
        """
        res = self.database.table(tier).get(Query().url == url)
        return Repository.from_dict(res) if res else None
```

- After, if the url is not find in the db the function raise an error:
```python
    def get_by_url(self, url: str) -> Repository:
        """
        Returns repository by URL.
        """
        data = self.storage.read()
        if url not in data:
            raise KeyError(f"No repo with URL '{url}'")
        return self.storage.read()[url]
```

**Comment by frankharkins** [comment]
That change broke the submission workflow, but why are we running tests on projects that don't exist in the ecosystem?
