### ISSUE TITLE
Project configuration in DB

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/ecosystem#52]
### What is the expected behavior?
Add ability to store project configuration in JSON Dao.

Order of configuration importance:
1. Config file
2. DB
3. Run default config

**Comment by mickahell** [comment]
@bala-ceg I'll help you, just I kind of forget how to do that ? 
I mean, i dont remember when do you get the config for each project or if we put it directly in the jsondb by hand and then the run process have to come in the jsondb and take the config (if the project does not have ecosystem.json file) or from another way ?

DO you remember @bala-ceg or @IceKhan13 ?

**Comment by IceKhan13** [comment]
@mickahell  yes, you are correct. We will manually add configs to db. Then if project has config file use it, else use config from db, else use default config
