### ISSUE TITLE
[Submission]: qiskit-classroom

### ISSUE THREAD

**Issue by minwook-shin** [qiskit-community/ecosystem#523]
### Github repo

https://github.com/KMU-quantum-classroom/qiskit-classroom

### Description

Qiskit-classroom is a toolkit that helps implement quantum algorithms by converting and visualizing different expressions used in the Qiskit ecosystem using Qiskit-classroom-converter. The following three transformations are supported : Quantum Circuit to Dirac notation, Quantum Circuit to Matrix, Matrix to Quantum Circuit etc...

### License

Apache License 2.0

### Labels

Visualization

### Website

https://github.com/KMU-quantum-classroom

**Comment by minwook-shin** [comment]
This GUI Application maintainer : fmowl10
cc. @fmowl10

**Comment by fmowl10** [comment]
https://github.com/qiskit-community/ecosystem/actions/runs/6092118171/job/16529733048#step:6:106
error occurs libegl not installed. we solved with this line 
https://github.com/KMU-quantum-classroom/qiskit-classroom/blob/331cb2776ef44143a34766752d8fed9b43467e2b/.github/workflows/python_tox.yml#L29C1-L29C46

**Comment by fmowl10** [comment]
is ecosystem.json can install depencies from debian packages?

**Comment by mickahell** [comment]
Hi @fmowl10 :)

As we have an `requirements-dev.txt` you need an ecosystem.json with this minimal conf :
```
{
    "dependencies_files": [
        "requirements.txt",
        "requirements-dev.txt"
    ]
}
```

About the debian package, currently we don't have this option but indeed it could be a good feature. I'll create an issue and thing about that. I'll came with a response during the week or week-end.

**Comment by mickahell** [comment]
@fmowl10 

I created you a PR for the ecosystem file : https://github.com/KMU-quantum-classroom/qiskit-classroom/pull/6

I did a test with my PR to add debian package and that's working, well. It probably be merged this week or next week.

**Comment by fmowl10** [comment]
I checked and merged your (My project) PR.
