### ISSUE TITLE
invite ecosystem members for follow up participation 

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-community/ecosystem#525]
Hello ecosystem platform developers, great work!

It would be great if, as part of the notification that the participant joint the platform, a message with follow up actions can be send (for closing the issue, for example?). Something like https://github.com/qiskit-community/ecosystem/issues/306#issuecomment-1561932217  

Let me know what do you think.

**Comment by mickahell** [comment]
Sure :) we could add that.

Shouldn't be complicate to automatize that from CI at closing issue.
