### ISSUE TITLE
[Submission]: qdao

### ISSUE THREAD

**Issue by Zhaoyilunnn** [qiskit-community/ecosystem#532]
### Github repo

https://github.com/Zhaoyilunnn/qdao

### Description

A lightweight framework to enable configurable memory consumption when simulating large quantum circuits.

### Email

zyilun8@gmail.com

### License

Apache License 2.0

### Affiliations

Institute of Computing Technology, Chinese Academy of Sciences.

### Labels

Circuit simulator

**Comment by mickahell** [comment]
Hi @Zhaoyilunnn :)

I saw your comment in the PR, we will see how we can manage that.
In the mean time, didn't you find any label that could correspond to your project at all ? If no, do you have suggestion for a label we could add ?

**Comment by Zhaoyilunnn** [comment]
> Hi @Zhaoyilunnn :)
> 
> I saw your comment in the PR, we will see how we can manage that. In the mean time, didn't you find any label that could correspond to your project at all ? If no, do you have suggestion for a label we could add ?

Hi @mickahell , thanks for the quick response. Sorry I missed the label section, after checking, I think qdao belongs to "Circuit simulator".

**Comment by mickahell** [comment]
> Hi @mickahell , thanks for the quick response. Sorry I missed the label section, after checking, I think qdao belongs to "Circuit simulator".

Can you edit your submission and add it please.

I update the tox file in my fork in order to take every GitHub Actions env var.
In my dry run I have this error :
```bash
ValueError: Cannot load qasm file random_12_9_max_operands_2_gen.qasm: [Errno 2] No such file or directory: '/home/runner/work/ecosystem/ecosystem/ecosystem/resources/cloned_repo_directory/qdao/qcs/benchmarks/qasm/random_12_9_max_operands_2_gen.qasm'
```

Log : https://github.com/mickahell/ecosystem/actions/runs/6212754899/job/16863200377#step:8:159

**Comment by mickahell** [comment]
Oh ok I saw why, you set the `qcs` folder in your tox : 
```python
python -c "import os; os.path.exists('{toxinidir}/qcs') or os.system('git clone https://github.com/Zhaoyilunnn/qcs.git {toxinidir}/qcs')"
```

Why do you do this in your tox and not in your tests as `def setUp(self) -> None:` ?

**Comment by Zhaoyilunnn** [comment]
> Oh ok I saw why, you set the `qcs` folder in your tox :
> 
> ```python
> python -c "import os; os.path.exists('{toxinidir}/qcs') or os.system('git clone https://github.com/Zhaoyilunnn/qcs.git {toxinidir}/qcs')"
> ```
> 
> Why do you do this in your tox and not in your tests as `def setUp(self) -> None:` ?
> 
> Example :
> 
> https://github.com/qiskit-community/ecosystem/blob/9c24cca89a1aa51070799fe70d340f8b12fbf5b4/tests/utils/test_utils.py#L14-L19
> 
> En then you can delete everything at the end of your test :
> 
> https://github.com/qiskit-community/ecosystem/blob/9c24cca89a1aa51070799fe70d340f8b12fbf5b4/tests/utils/test_utils.py#L14-L19

Got it, thanks a lot! I will fix this issue and get back to you.

**Comment by mickahell** [comment]
> Got it, thanks a lot! I will fix this issue and get back to you.

No problem :)

If you want to run something at the end of your tests you can also add :
https://github.com/qiskit-community/ecosystem/blob/9c24cca89a1aa51070799fe70d340f8b12fbf5b4/tests/runners/test_runner.py#L20-L25

**Comment by Zhaoyilunnn** [comment]
Hi @mickahell, I have fixed `qcs` setting issue and added the label. Please check it. Thanks!

**Comment by mickahell** [comment]
> Hi @mickahell, I have fixed `qcs` setting issue and added the label. Please check it. Thanks!

You were fast !
I'm testing it in my fork

**Comment by mickahell** [comment]
New error :

```bash
tests/qdao/engine_test.py::TestEngine::test_run_qiskit_any_qasm[random_12_9_max_operands_2_gen.qasm-12-10-8-QDAO-1-1-CPU-disk] - PermissionError: [Errno 13] Permission denied: '/root/projects/qcs'
```

**Comment by Zhaoyilunnn** [comment]
> New error :
> 
> ```shell
> tests/qdao/engine_test.py::TestEngine::test_run_qiskit_any_qasm[random_12_9_max_operands_2_gen.qasm-12-10-8-QDAO-1-1-CPU-disk] - PermissionError: [Errno 13] Permission denied: '/root/projects/qcs'
> ```
> 
> Log : https://github.com/mickahell/ecosystem/actions/runs/6213059508/job/16863769683#step:6:251

I see it and have fixed it. Thanks

**Comment by mickahell** [comment]
> I see it and have fixed it. Thanks

Ok I'm sending a new dry run

**Comment by Zhaoyilunnn** [comment]
> > I see it and have fixed it. Thanks
> 
> Ok I'm sending a new dry run

Thanks. I will add a github action in my repo to avoid mistakes corresponding to local development environment...

**Comment by mickahell** [comment]
> Thanks. I will add a github action in my repo to avoid mistakes corresponding to local development environment...

Success 🥳 Summary result : https://github.com/mickahell/ecosystem/actions/runs/6213099084/attempts/1#summary-16863841344
Everything seems to works fine now :) 

From what I see from our check result is you could also use the latest qiskit version : `0.44.1`

Don't forget to add in your tox this line `passenv = *` under `[testenv]` in order to pass every env var from Actions to tox.

**Comment by mickahell** [comment]
And now in order to your submission to pass. It just need to merge this PR #537 , gonna be merge during next week I guess.

**Comment by Zhaoyilunnn** [comment]
> > Thanks. I will add a github action in my repo to avoid mistakes corresponding to local development environment...
> 
> Success 🥳 Summary result : https://github.com/mickahell/ecosystem/actions/runs/6213099084/attempts/1#summary-16863841344 Everything seems to works fine now :)
> 
> From what I see from our check result is you could also use the latest qiskit version : `0.44.1`
> 
> Don't forget to add in your tox this line `passenv = *` under `[testenv]` in order to pass every env var from Actions to tox.

Sure! Thanks for reminding, btw I checked that the dev version test failed, but the issue can also be fixed. We will keep pace with qiskit development and make it compatible with latest qiskit version.

**Comment by mickahell** [comment]
For the submission the minimal requirements is to pass the standard check. If can pass stable as well is great and if pass all 3 that's perfect :D and means your program is very strong and should be able to evolve through Qiskit evolution 🚀

**Comment by Zhaoyilunnn** [comment]
> For the submission the minimal requirements is to pass the standard check. If can pass stable as well is great and if pass all 3 that's perfect :D and means your program is very strong and should be able to evolve through Qiskit evolution 🚀

Thanks for the illustration, I think the dev version test should also be passed now :)

**Comment by mickahell** [comment]
> Thanks for the illustration, I think the dev version test should also be passed now :)

Congrat's : https://github.com/mickahell/ecosystem/actions/runs/6213616184/attempts/1#summary-16864837484 ;)
