### ISSUE TITLE
[Submission]: qiskit-qubit-reuse

### ISSUE THREAD

**Issue by mtreinish** [qiskit-community/ecosystem#549]
### Github repo

https://github.com/qiskit-community/qiskit-qubit-reuse

### Description

A Qiskit transpiler stage plugin to enable qubit reuse via mid-circuit measurement and reset. 

### License

Apache License 2.0

### Affiliations

IBM

### Labels

Paper implementation, Transpiler plugin

**Comment by mickahell** [comment]
Just seems to be a network problem :) let's retry

**Comment by mickahell** [comment]
Hello @mtreinish :)

I don't see any unit test in your project. To pass the check of the Ecosystem it need at least one.
As it's seems to be an IBM project we can add it with `test = false` in the project TOML but I'll let @frankharkins judge of that.

**Comment by frankharkins** [comment]
Skipping the tests is fine. If it's easy enough, a smoke test to check the pass "works" against future Qiskit versions would be ideal.
