### ISSUE TITLE
[Submission]: qiskit-aqt-provider

### ISSUE THREAD

**Issue by airwoodix** [qiskit-community/ecosystem#562]
### Github repo

https://github.com/qiskit-community/qiskit-aqt-provider

### Description

Qiskit provider for ion-trap quantum computers from Alpine Quantum Technologies (AQT). https://www.aqt.eu/qc-systems/

### Email

[info@aqt.eu](mailto:info@aqt.eu)

### License

Apache License 2.0

### Affiliations

Alpine Quantum Technologies GmbH

### Labels

Provider

### Website

https://qiskit-community.github.io/qiskit-aqt-provider/

**Comment by airwoodix** [comment]
@IceKhan13 Above mentioned PRs have been merged in [qiskit-community/qiskit-aqt-provider](https://github.com/qiskit-community/qiskit-aqt-provider). Would it be an option to re-trigger the integration pipeline? Thanks!

**Comment by frankharkins** [comment]
Hi @airwoodix! I'll retrigger now, although we'll soon stop supporting the testing feature so I'm happy to add `qiskit-aqt-provider` even if the tests don't pass.

**Comment by frankharkins** [comment]
@airwoodix could you add a contact email too please?

**Comment by airwoodix** [comment]
Awesome, thanks!

> we'll soon stop supporting the testing feature

Does that mean that we wouldn't need to expose `requirements.txt` anymore? This would make it significantly more convenient for us, since our dependencies are specified in `pyproject.toml`.

**Comment by frankharkins** [comment]
> Awesome, thanks!
> 
> > we'll soon stop supporting the testing feature
> 
> Does that mean that we wouldn't need to expose `requirements.txt` anymore? This would make it significantly more convenient for us, since our dependencies are specified in `pyproject.toml`.

Yep that's fine, sorry for the poor communication.
