### ISSUE TITLE
Add metadata description to Ecosystem site

### ISSUE THREAD

**Issue by Eric-Arellano** [qiskit-community/ecosystem#569]
This requires coming up with copy for what to put in the description. Then, adding code like this to the `<head>` of the `index.html`:

```html
<meta name="description" content="Some tags are vital for SEO. Others have little or no impact on rankings. Here's every type of meta tag you need to know about.The purpose of a meta description is to reflect the essence of a page, but with more details and context."/>
```

**Comment by frankharkins** [comment]
RE copy, maybe the tagline from the page would work:
> Explore projects that use or extend Qiskit

**Comment by Eric-Arellano** [comment]
Implemented in https://github.com/qiskit-community/ecosystem/pull/559
