### ISSUE TITLE
[Submission]: ecosystem template

### ISSUE THREAD

**Issue by mickahell** [qiskit-community/ecosystem#76]
### Github repo

https://github.com/mickahell/qiskit-ecosystem_template

### Description

Project template for adding to Qiskit Ecosystem

### Email

michael.rollin@protonmail.com

### License

Apache License 2.0

### Affiliations

Qiskit community

### Tags

tool

**Comment by IceKhan13** [comment]
!redo

**Comment by mickahell** [comment]
!redo

**Comment by mickahell** [comment]
!redo

**Comment by IceKhan13** [comment]
!redo

**Comment by mickahell** [comment]
Hahah it's on me, I forget to create the var 
https://github.com/qiskit-community/ecosystem/blob/e6ab4188f86de20cf725d25e51074ffa677a51b8/ecosystem/runners/runner.py#L140-L144

**Comment by IceKhan13** [comment]
!redo

**Comment by mickahell** [comment]
!redo
