### ISSUE TITLE
EPIC: QAMP fall 2021

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/ecosystem#9]
**EPIC for QAMP fall 2021 Ecosystem project**

Main task for 2021 fall QAMP ecosystem project will be rolling out support for community tier a.k.a projects developed by community.

Personas:

- community member of ecosystem
- developer/contributor of ecosystem repository
- core team member/curator

Stories:

- as community member of ecosystem I want to be able to submit my project so that it would be included into ecosystem
- as community member of ecosystem I want to be notified when my project is lacking behind stable / dev versions of Qiskit so that I would be able to update my codebase
- as community member of ecosystem I want my project to be displayed in ecosystem github README and qiskit.org 
- as community member of ecosystem I want to receive membership badge so that it would demonstrate my ecosystem membership
- as developer/contributor of ecosystem repository I want to be able to propose new features for ecosystem
- as developer/contributor of ecosystem repository I want ecosystem management independent of platform so that it can be executed on any CI/CD framework
- as core team member/curator I want to be able to review submissions to ecosystem 
- as core team member/curator I want CI processes takes care of tests, style checks, coverage after submission so that it would reduce time of review of submission
- as core team member/curator I want members of ecosystem tiers are stored as json serialized file within repository so that it can be used as reference database
- as core team member/curator I want README for repository to be generated automatically after each change of members
- as core team member/curator I want CI processes create PRs with members changes in case of successful tests/checks so that only thing remaining to include project into ecosystem would be merging PR
- as core team member/curator I want CI for tests/checks to be executed in timely manner (weekly) so that entire ecosystem always remains up-to-date 
- as core team member/curator I want checks and tests to have Terra version associated with them so that we can track which version is breaking the code
- as core team member/curator I want track list of changes in members (diff between current and next version of members json)
- as core team member/curator I want badging system to be automated so that badges dynamically checks repository membership (ex: gray if checks did not passed or purple of checks passed)
- as core team member/curator I want ecosystem community tier to be separated into 3 subgroups: community member lvl 1, community member lvl 2 and candidate so that community member lvl 1 is project that checks all tests in guidelines (tests, coverage, code style), community member lvl 2 did not have enough coverage, candidate have tests or styles missing or failed

**Ecosystem maintenance**:
- tiers
  - main
  - member
  - candidate
  - custom tiers:
    - partners
    - research / universities
- main is curated
- candidate/members
  - if candidate passed all checks move it to members
  - if member did not passed tests move it to candidate
- separate workflows for main and custom tiers

**Submission**:
- template parser
- tests runs: stable, dev, linter
- add new entry to candidate tier if tests passed
- create PR to add to candidates

**Badges system**:
- members badge 
- api backend for badges checks (https://github.com/marketplace/actions/dynamic-badges)

**Comment by IceKhan13** [comment]
@mickahell @bala-ceg you are both great! we did it!

**Comment by mickahell** [comment]
> @mickahell @bala-ceg you are both great! we did it!

YEEEAAAAAH 🥳
